version: '3'
services:
  devenv: 
    image: budakf/cpp-dev-env:v0.4
    volumes:
      - ..:/workspace:cached
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    command: /bin/sh -c "while sleep 1000; do :; done"  
